import { Metadata } from "next";
import "./globals.css";
import NavbarClient from '../components/common/NavbarClient';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarClient />
        {children}
      </body>
    </html>
  );
}
